version: "3"
services:
    data-service:
        image: node:14.17.0
        container_name: data-service
        working_dir: /src
        depends_on:
          - mongodb
        ports:
          - "8080:8080"
        volumes:
          - "./:/src"
        restart: unless-stopped
        environment:
          PORT: 8080
          MONGO_URL: 'mongodb://admin:pass@mongodb:27017/universities'
        command: bash -c "npm run start"
    
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
          - "27017:27017"
        volumes:
          - "./:/src"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "pass"
            MONGO_INITDB_DATABASE: admin
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ui-mongo:
        image: mongo-express:latest
        container_name: ui-mongo
        depends_on:
        - mongodb
        restart: always
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass